steps:
  - name: gcr.io/cloud-builders/yarn
    args: 
      - install
  - name: gcr.io/cloud-builders/yarn
    args: 
      - build
      - -o
      - /build
    volumes:
      - name: build
        path: /build
  - name: gcr.io/cloud-builders/gsutil
    args: 
      - -m
      - rsync
      - -r
      - -c
      - -d
      - /build
      - gs://syrianmusic.org
    volumes:
      - name: build
        path: /build
