nav:
  performance:
    text: Performance
    href: /performance
    description: >
      Learn more about past and future performances of Takht al-Nagham.
    image:
      src: /images/home-nav-performance.jpg
      width: 480
      height: 316
      srcSet:
        - densityFactor: 2
          src: /images/home-nav-performance@2x.jpg
        - densityFactor: 3
          src: /images/home-nav-performance@3x.jpg
    links:
      - text: Takht al-Nagham
        href: /
      - text: Raqs al-Samah
        href: /
  education:
    text: Education
    href: /education
    description: >
      Learn about Syrian music through biographies, transcriptions, lyrical translation and
       musicological analysis. An exploration of this tradition from any level. Explore additional
       resources, workshops and our beautiful oud collection.
    image:
      src: /images/home-nav-education.jpg
      width: 480
      height: 316
      srcSet:
        - densityFactor: 2
          src: /images/home-nav-education@2x.jpg
        - densityFactor: 3
          src: /images/home-nav-education@3x.jpg
    links:
      - text: Musical Figures and Bios
        href: /
        description: >
          Learn about the people who have influenced the course of the Syrian musical tradition,
           including biographies, important works and historical context.
      - text: Transcriptions
        href: /
        description: View SMPI’s archive of transcribed works.
      - text: Lyrics & Translations
        href: /
        description: >
          Understanding the lyrics to pieces is key to unlocking the feelings within a piece.
           Search through our lyrical database to find lyrics in Arabic translated into other
           languages and some brief poetic analysis.
      - text: Musical Forms
        href: /
        description: >
          Gain a deeper understanding of the key musical structures within Syrian (and Arab) musical
           tradition.
      - text: Maqams
        href: /
        description: >
          Maqams are the building block of all Syrian music.  Learn the foundations of each of the
           maqams, why they are different and hear them in context of real pieces.
      - text: Ouds
        href: /
        description: View the beautiful Oud collection in our online museum.
      - text: Resources & References
        href: /
        description: >
          Read from our digital library of books on Syrian music, forms and people in Arabic and
           English and get additional information from some of our partner sites and organizations.
      - text: Lessons & Workshops
        href: /
        description: Study with us virtually and in person!
  about:
    text: About
    href: /about
    description: >
      Learn more about the SMPI mission, members, and more.
    image:
      src: /images/home-nav-about.jpg
      width: 480
      height: 316
      srcSet:
        - densityFactor: 2
          src: /images/home-nav-about@2x.jpg
        - densityFactor: 3
          src: /images/home-nav-about@3x.jpg
  connect:
    text: Connect
    href: /connect
    description: >
      Join our community by following us on social media, signing up for our newsletter,
       volunteering or donating.
    image:
      src: /images/home-nav-connect.jpg
      width: 480
      height: 316
      srcSet:
        - densityFactor: 2
          src: /images/home-nav-connect@2x.jpg
        - densityFactor: 3
          src: /images/home-nav-connect@3x.jpg
    links:
      donate:
        text: Donate
        href: https://secure.squarespace.com/checkout/donate?donatePageId=5bc627f90852298e0d320f3d&ss_cid=98821902-8f9b-4383-bf30-abb211822fb7&ss_cvr=f522a8b6-588a-417b-b949-6da49a78d160%7C1583903323850%7C1585024825658%7C1585072215232%7C18
      facebook:
        text: Facebook
        href: https://www.facebook.com/takhtalnagham
      instagram:
        text: Instagram
        href: https://www.instagram.com/takhtalnagham/

