nav:
  performance:
    text: Performance
    href: /performance
    description: >
      Learn more about past and future performances of Takht al-Nagham.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
    links:
      - text: Takht al-Nagham
        href: /
      - text: Raqs al-Samah
        href: /
  education:
    text: Education
    href: /education
    description: >
      Learn about Syrian music through biographies, transcriptions, lyrical translation and
       musicological analysis. An exploration of this tradition from any level. Explore additional
       resources, workshops and our beautiful oud collection.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
    links:
      - text: Musical Figures and Bios
        href: /
      - text: Transcriptions
        href: /
      - text: Musical Forms
        href: /
      - text: Maqams
        href: /
      - text: Ouds
        href: /
      - text: Resources & References
        href: /
      - text: Workshops
        href: /
  about:
    text: About
    href: /about
    description: >
      Learn more about the SMPI mission, members, and more.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
  connect:
    text: Connect
    href: /connect
    description: >
      Join our community by following us on social media, signing up for our newsletter, volunteering or donating.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
    links:
      donate:
        text: Donate
        href: https://secure.squarespace.com/checkout/donate?donatePageId=5bc627f90852298e0d320f3d&ss_cid=98821902-8f9b-4383-bf30-abb211822fb7&ss_cvr=f522a8b6-588a-417b-b949-6da49a78d160%7C1583903323850%7C1585024825658%7C1585072215232%7C18
      facebook:
        text: Facebook
        href: https://www.facebook.com/takhtalnagham
      instagram:
        text: Instagram
        href: https://www.instagram.com/takhtalnagham/

