nav:
  education:
    text: Education
    href: /education
    description: >
      Explore performance notes on specific performances by the organization, explanations on musical forms, glossaries, workshops, and more.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
  about:
    text: About
    href: /about
    description: >
      Learn more about the SMPI, its story, mission, members, and more.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
  connect:
    text: Connect
    href: /connect
    description: >
      Find out how to connect with us, donate, and become a member. We want to hear from you.
    image:
      src: /images/home-nav-item.jpg
      width: 957
      height: 539
    links: 
      donate:
        text: Donate
        href: https://secure.squarespace.com/checkout/donate?donatePageId=5bc627f90852298e0d320f3d&ss_cid=98821902-8f9b-4383-bf30-abb211822fb7&ss_cvr=f522a8b6-588a-417b-b949-6da49a78d160%7C1583903323850%7C1585024825658%7C1585072215232%7C18
      facebook:
        text: Facebook
        href: https://www.facebook.com/takhtalnagham
      instagram:
        text: Instagram
        href: https://www.instagram.com/takhtalnagham/

