nav:
  performance:
    text: Performance
    href: /performance
    description: >
      Learn more about past and future performances of Takht al-Nagham.
    image:
      src: /images/instruments/syrian-tambourine.png
      width: 432
      height: 287
      srcSet:
        - densityFactor: 2
          src: /images/instruments/syrian-tambourine@2x.png
        - densityFactor: 3
          src: /images/instruments/syrian-tambourine@3x.png
    links:
      - text: Takht al-Nagham
        href: /#takht-al-nagham
  education:
    text: Education
    href: /education
    description: >
      Learn about Syrian music through biographies, transcriptions, lyrical translation and
       musicological analysis. An exploration of this tradition from any level. Explore additional
       resources, workshops and our beautiful oud collection.
    image:
      src: /images/instruments/two-syrian-ouds.png
      width: 432
      height: 288
      srcSet:
        - densityFactor: 2
          src: /images/instruments/two-syrian-ouds@2x.png
        - densityFactor: 3
          src: /images/instruments/two-syrian-ouds@3x.png
    links:
      - text: Musical Figures & Bios
        href: /
        description: >
          Learn about the people who have influenced the course of the Syrian musical tradition,
           including biographies, important works and historical context.
      - text: Transcriptions
        href: /
        description: View SMPI’s archive of transcribed works.
      - text: Lyrics & Translations
        href: /
        description: >
          Understanding the lyrics to pieces is key to unlocking the feelings within a piece.
           Search through our lyrical database to find lyrics in Arabic translated into other
           languages and some brief poetic analysis.
      - text: Musical Forms
        href: /
        description: >
          Gain a deeper understanding of the key musical structures within Syrian (and Arab) musical
           tradition.
      - text: Maqams
        href: /
        description: >
          Maqams are the building block of all Syrian music.  Learn the foundations of each of the
           maqams, why they are different and hear them in context of real pieces.
      - text: Ouds
        href: /
        description: View the beautiful Oud collection in our online museum.
      - text: Resources & References
        href: /
        description: >
          Read from our digital library of books on Syrian music, forms and people in Arabic and
           English and get additional information from some of our partner sites and organizations.
      - text: Lessons & Workshops
        href: /
        description: Study with us virtually and in person!
  about:
    text: About
    href: /about
    description: >
      Learn more about the SMPI mission, members, and more.
    image:
      src: /images/instruments/syrian-oud-side-profile.png
      width: 431.5
      height: 286
      srcSet:
        - densityFactor: 2
          src: /images/instruments/syrian-oud-side-profile@2x.png
        - densityFactor: 3
          src: /images/instruments/syrian-oud-side-profile@3x.png
    links:
      - text: Mission
        href: /#mission
      - text: Our Story
        href: /#our-story
      - text: Who We Are
        href: /#who-we-are
  connect:
    text: Connect
    href: /connect
    description: >
      Join our community by following us on social media, signing up for our newsletter,
       volunteering or donating.
    image:
      src: /images/instruments/syrian-oud-strings.png
      width: 432
      height: 288
      srcSet:
        - densityFactor: 2
          src: /images/instruments/syrian-oud-strings@2x.png
        - densityFactor: 3
          src: /images/instruments/syrian-oud-strings@3x.png
    links:
      donate:
        text: Donate
        href: https://secure.squarespace.com/checkout/donate?donatePageId=5bc627f90852298e0d320f3d&ss_cid=98821902-8f9b-4383-bf30-abb211822fb7&ss_cvr=f522a8b6-588a-417b-b949-6da49a78d160%7C1583903323850%7C1585024825658%7C1585072215232%7C18
      facebook:
        text: Facebook
        href: https://www.facebook.com/takhtalnagham
      instagram:
        text: Instagram
        href: https://www.instagram.com/takhtalnagham/

