nav:
  performance:
    text: Performance
    homeText: Upcoming Events
    href: /performance
    description: >
      Learn about future Takht al-Nagham performances.
    image:
      src: /images/takht-al-nagham/takht-al-nagham-1.png
      width: 427
      height: 294
      srcSet:
        - densityFactor: 2
          src: /images/takht-al-nagham/takht-al-nagham-1@2x.png
        - densityFactor: 3
          src: /images/takht-al-nagham/takht-al-nagham-1@3x.png
    links:
      - text: Takht al-Nagham
        href: /performance/#takht-al-nagham
  education:
    text: Education
    homeText: Repertoire
    href: /education
    homeHref: /education/transcriptions
    description: >
      Explore compositions and download sheet music from a variety of composers in an easy to search layout.
    image:
      src: /images/sheet-music/open-book-with-syrian-sheet-music.png
      width: 432
      height: 288
      srcSet:
        - densityFactor: 2
          src: /images/sheet-music/open-book-with-syrian-sheet-music@2x.png
        - densityFactor: 3
          src: /images/sheet-music/open-book-with-syrian-sheet-music@3x.png
    links:
      - text: Repertoire
        href: /education/transcriptions
        description: >
          View our archive of transcribed works.
      - text: Biographies
        href: /
        description: >
          Learn about the people who have influenced the course of the Syrian musical tradition, including biographies, important works and historical context.
      - text: Musical Forms
        href: /
        description: >
          Get a deeper understanding of the key musical structures within Syrian (and Arab) musical tradition.
      - text: Artist-in-Residence
        href: /
        description: >
          Learn about SMPI's Artist-in-Residence Program which commissions works from artists internationally.
      - text: Ouds
        href: /
        description: >
          View the beautiful Oud collection in our online museum.
  about:
    text: About
    homeText: Meet Our People
    href: /about
    description: >
      Learn more about our story, mission, members, and more.
    image:
      src: /images/instruments/syrian-oud-side-profile.png
      width: 431.5
      height: 286
      srcSet:
        - densityFactor: 2
          src: /images/instruments/syrian-oud-side-profile@2x.png
        - densityFactor: 3
          src: /images/instruments/syrian-oud-side-profile@3x.png
    links:
      - text: Mission
        href: /about/#mission
      - text: Our Story
        href: /about/#our-story
      - text: Who We Are
        href: /about/#who-we-are
  connect:
    text: Connect
    href: /connect
    description: >
      Find out how to connect with us, donate, and become a member. We want to hear from you.
    image:
      src: /images/instruments/syrian-oud-strings.png
      width: 432
      height: 288
      srcSet:
        - densityFactor: 2
          src: /images/instruments/syrian-oud-strings@2x.png
        - densityFactor: 3
          src: /images/instruments/syrian-oud-strings@3x.png
    links:
      donate:
        text: Donate
        href: /donate
      facebook:
        text: Facebook
        href: https://facebook.com/syrianmusicpi
        showInFooter: false
      instagram:
        text: Instagram
        href: https://instagram.com/syrianmusicpi
        showInFooter: false
