version: "3"

services:
  web:
    image: syrian_music
    command: yarn netlify dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    container_name: syrian_music_web
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "8888:8888"

  storybook:
    image: syrian_music
    command: yarn start-storybook -p 9999 -s ./public
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syrian_music_storybook
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "9999:9999"

  tests:
    image: syrian_music
    command: yarn jest --watch
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syrian_music_tests
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    name: syrian_music_node_modules
    external: false
