version: "3"

services:
  web:
    image: syrian_music
    command: yarn netlify dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env.docker
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "8888:8888"

  storybook:
    image: syrian_music
    command: yarn start-storybook -p 6006 -s ./public
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storybook
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "6006:6006"

volumes:
  node_modules:
    name: syrian_music_node_modules
    external: false
