export default {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'amount_too_small',
    doc_url: 'https://stripe.com/docs/error-codes/amount-too-small',
    message: 'Amount must be at least $0.50 usd',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Tue, 30 Aug 2022 05:46:00 GMT',
      'content-type': 'application/json',
      'content-length': '212',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers':
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'idempotency-key': '8054b84d-664b-409e-9cbf-16f30618e242',
      'original-request': 'req_m1s59s1H3tUWxj',
      'request-id': 'req_m1s59s1H3tUWxj',
      'stripe-should-retry': 'false',
      'stripe-version': '2022-08-01',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
    },
    statusCode: 400,
    requestId: 'req_m1s59s1H3tUWxj',
  },
  rawType: 'invalid_request_error',
  code: 'amount_too_small',
  doc_url: 'https://stripe.com/docs/error-codes/amount-too-small',
  param: undefined,
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Tue, 30 Aug 2022 05:46:00 GMT',
    'content-type': 'application/json',
    'content-length': '212',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers':
      'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'idempotency-key': '8054b84d-664b-409e-9cbf-16f30618e242',
    'original-request': 'req_m1s59s1H3tUWxj',
    'request-id': 'req_m1s59s1H3tUWxj',
    'stripe-should-retry': 'false',
    'stripe-version': '2022-08-01',
    'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
  },
  requestId: 'req_m1s59s1H3tUWxj',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined,
};
