export default {
  type: 'StripeAuthenticationError',
  raw: {
    message:
      "You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.",
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Tue, 30 Aug 2022 05:38:45 GMT',
      'content-type': 'application/json',
      'content-length': '343',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers':
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'www-authenticate': 'Basic realm="Stripe"',
      'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
    },
    statusCode: 401,
    requestId: undefined,
  },
  rawType: 'invalid_request_error',
  code: undefined,
  doc_url: undefined,
  param: undefined,
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Tue, 30 Aug 2022 05:38:45 GMT',
    'content-type': 'application/json',
    'content-length': '343',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers':
      'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'www-authenticate': 'Basic realm="Stripe"',
    'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
  },
  requestId: undefined,
  statusCode: 401,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined,
};
